[package]
name = "pretty_text_effects"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_text = { path = "../pretty_text" }
pretty_text_macros = { path = "../macros" }

bevy = { workspace = true }
rand = "0.9.1"
