name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: typos
        run: cargo install typos-cli && cargo typos

      - name: clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: test
        run: cargo test --workspace --all-features

      - name: release
        run: cargo build --release --workspace --all-features

      - name: format
        run: cargo fmt --all -- --check
